Include Get in the UpdateRetry. (#82)
This adjusts the update retry around the ingress update in #79 to include the Get.

The original change was to guard against issues updating gke-resource-quotas, but there is a low incidence of conflicts simply updating the kingress itself.

Here's an example from net-contour:

```
=== CONT  TestIngressConformance/5/update
    update.go:88: Error updating Ingress: Operation cannot be fulfilled on ingresses.networking.internal.knative.dev "ingress-conformance-5-update-eghinekn": the object has been modified; please apply your changes to the latest version and try again
```

However, to resolve this, we actually have to refetch the kingress shell we've stuck the desired IngressSpec into otherwise it will just retry until it has exhausted its attempts because the resourceVersion we're sending back is never changed (and this is what the optimistic concurrency keys off of).